name = "SatcomCoordinates"
uuid = "d1ae2422-d5a1-41ba-aa52-f237f2f47a73"
authors = ["Alberto Mengali <disberd@gmail.com>"]
version = "0.1.0"

[deps]
BasicTypes = "13e19751-ccd1-416d-be0c-a6724a8caa31"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TransformsBase = "28dd2a49-a57a-4bfb-84ca-1a49db9b96b8"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[weakdeps]
CountriesBorders = "ee40d4b5-31c3-4fe2-b6cc-5ac7adf7f414"
SatelliteToolboxBase = "9e17983a-0463-41a7-9a16-1682db6d8b66"
SatelliteToolboxTransformations = "6b019ec1-7a1e-4f04-96c7-a9db1ca5514d"

[extensions]
CountriesBordersExt = ["CountriesBorders"]
SatelliteToolboxBaseExt = ["SatelliteToolboxBase"]
SatelliteToolboxTransformationsExt = ["SatelliteToolboxTransformations", "SatelliteToolboxBase"]

[compat]
BasicTypes = "1.3"
ConstructionBase = "1.5.8"
CountriesBorders = "0.4.0"
LinearAlgebra = "1"
Random = "1"
Rotations = "1.7.1"
SatelliteToolboxBase = "1"
SatelliteToolboxTransformations = "1"
StaticArrays = "1.9.10"
TransformsBase = "1.6.0"
Unitful = "1.22"
julia = "1.11"
